start_msg: |
      ุจุฑุง ุงูฺฉู ุงุทูุงุนุงุช ุงฺฉุงูุช ุฑู ุจุจูุฏ ููฺฉ ุงฺฉุงูุช ฺฉู ุงุฒ ูุง ฺฏุฑูุชุฏ ุฑุง ูุงุฑุฏ ฺฉูุฏ.

help_msg: |
      

not_found: "<b>๐ุงุทูุงุนุงุช ุงฺฉุงูุช ุดูุง ูพุฏุง ูุดุฏ!</b> \n ูุทูุฆูุฏ <b>UUID - Vless - Vmess - remark</b> ุฑู ุฏุฑุณุช ูุงุฑุฏ ฺฉุฑุฏูุ \n ุงฺฏู ููุฏููู ฺุฌูุฑ ฺฉ ุงุฒูุง ุฑู ุจุฏุณุช ุจุงุฑู ุฑู /what ุจุฒูุฏ... \n  ูุณุจุช ุจู ุงูฺฉู ฺู ูุฑู ุงูุฒุงุฑ ูุตุจ ุฏุงุฑู ุจู ุดูุง ฺฉูฺฉ ูฺฉูู."
acc_info: ๐ ุงุทูุงุนุงุช ุณุฑูุณ ุดูุง ุชุง ุงู ูุญุธู ๐
whatapp_msg: 
